# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=b'documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.TextField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('launch_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('slug', models.CharField(max_length=30)),
                ('required_documents', models.ManyToManyField(to='app.Documents')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'MIN_AGE', b'MIN_AGE'), (b'MAX_AGE', b'MAX_AGE'), (b'BANK_ACC_NO', b'BANK_ACC_NO'), (b'EDUCATIONAL_QUALIFICATION', b'EDUCATIONAL_QUALIFICATION'), (b'NATIONALITY', b'NATIONALITY'), (b'SAVINGS_ACC', b'SAVINGS_ACC'), (b'MAX_NO_OF_GIRL_CHILDREN', b'MAX_NO_OF_GIRL_CHILDREN'), (b'MAX_NO_OF_CHILDREN', b'MAX_NO_OF_CHILDREN'), (b'GENDER', b'GENDER'), (b'CASTE', b'CASTE'), (b'MARITAL_STATUS', b'MARITAL_STATUS'), (b'MIN_SALARY', b'MIN_SALARY'), (b'MAX_SALARY', b'MAX_SALARY'), (b'PREGNANT', b'PREGNANT'), (b'FARMER', b'FARMER'), (b'NO_OF_WORKING_YEARS', b'NO_OF_WORKING_YEARS'), (b'NO_OF_WORKING_YEARS', b'NO_OF_WORKING_YEARS'), (b'EXCELLED_IN_ANY_SPOT', b'EXCELLED_IN_ANY_SPOT'), (b'EMPLOYED', b'EMPLOYED'), (b'DISABLED', b'DISABLED'), (b'IS_ENTREPRENEUR', b'IS_ENTREPRENEUR')], max_length=30)),
                ('type', models.CharField(choices=[(b'NUMERIC', b'NUMERIC'), (b'LIST', b'LIST'), (b'BOOLEAN', b'BOOLEAN')], max_length=10)),
                ('Required_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_criteria_vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN_AGE', models.IntegerField(null=True)),
                ('MAX_AGE', models.IntegerField(null=True)),
                ('BANK_ACC_NO', models.BooleanField()),
                ('EDUCATIONAL_QUALIFICATION', models.CharField(max_length=30)),
                ('IS_INDIAN', models.BooleanField()),
                ('SAVINGS_ACC', models.BooleanField()),
                ('MAX_NO_OF_GIRL_CHILDREN', models.IntegerField(null=True)),
                ('MAX_NO_OF_CHILDREN', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[(b'Male', b'male'), (b'female', b'female')], max_length=10)),
                ('CASTE', models.CharField(max_length=20)),
                ('MARITAL_STATUS', models.BooleanField()),
                ('MIN_SALARY', models.IntegerField(null=True)),
                ('MAX_SALARY', models.IntegerField(null=True)),
                ('PREGNANT', models.BooleanField()),
                ('FARMER', models.BooleanField()),
                ('NO_OF_WORKING_YEARS', models.IntegerField(null=True)),
                ('MARKS_PERCENT', models.IntegerField(null=True)),
                ('EXCELLED_IN_ANY_SPOT', models.TextField(null=True)),
                ('EMPLOYED', models.BooleanField()),
                ('DISABLED', models.BooleanField()),
                ('IS_ENTREPRENEUR', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_criteria_vertical_bool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN_AGE', models.BooleanField()),
                ('MAX_AGE', models.BooleanField()),
                ('BANK_ACC_NO', models.BooleanField()),
                ('EDUCATIONAL_QUALIFICATION', models.BooleanField()),
                ('IS_INDIAN', models.BooleanField()),
                ('SAVINGS_ACC', models.BooleanField()),
                ('MAX_NO_OF_GIRL_CHILDREN', models.BooleanField()),
                ('MAX_NO_OF_CHILDREN', models.BooleanField()),
                ('Gender', models.BooleanField()),
                ('CASTE', models.BooleanField()),
                ('MARITAL_STATUS', models.BooleanField()),
                ('MIN_SALARY', models.BooleanField()),
                ('MAX_SALARY', models.BooleanField()),
                ('PREGNANT', models.BooleanField()),
                ('FARMER', models.BooleanField()),
                ('NO_OF_WORKING_YEARS', models.BooleanField()),
                ('MARKS_PERCENT', models.BooleanField()),
                ('EXCELLED_IN_ANY_SPOT', models.BooleanField()),
                ('EMPLOYED', models.BooleanField()),
                ('DISABLED', models.BooleanField()),
                ('IS_ENTREPRENEUR', models.BooleanField()),
                ('SCHEME', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='scheme_criteria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scheme_criteria_vertical'),
        ),
    ]
