# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.TextField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('launch_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('slug', models.CharField(max_length=30)),
                ('required_documents', models.ManyToManyField(to='app.Documents')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MIN_AGE', 'MIN_AGE'), ('MAX_AGE', 'MAX_AGE'), ('BANK_ACC_NO', 'BANK_ACC_NO'), ('EDUCATIONAL_QUALIFICATION', 'EDUCATIONAL_QUALIFICATION'), ('NATIONALITY', 'NATIONALITY'), ('SAVINGS_ACC', 'SAVINGS_ACC'), ('MAX_NO_OF_GIRL_CHILDREN', 'MAX_NO_OF_GIRL_CHILDREN'), ('MAX_NO_OF_CHILDREN', 'MAX_NO_OF_CHILDREN'), ('GENDER', 'GENDER'), ('CASTE', 'CASTE'), ('MARITAL_STATUS', 'MARITAL_STATUS'), ('MIN_SALARY', 'MIN_SALARY'), ('MAX_SALARY', 'MAX_SALARY'), ('PREGNANT', 'PREGNANT'), ('FARMER', 'FARMER'), ('NO_OF_WORKING_YEARS', 'NO_OF_WORKING_YEARS'), ('NO_OF_WORKING_YEARS', 'NO_OF_WORKING_YEARS'), ('EXCELLED_IN_ANY_SPOT', 'EXCELLED_IN_ANY_SPOT'), ('EMPLOYED', 'EMPLOYED'), ('DISABLED', 'DISABLED'), ('IS_ENTREPRENEUR', 'IS_ENTREPRENEUR')], max_length=30)),
                ('type', models.CharField(choices=[('NUMERIC', 'NUMERIC'), ('LIST', 'LIST'), ('BOOLEAN', 'BOOLEAN')], max_length=10)),
                ('Required_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_criteria_vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN_AGE', models.IntegerField()),
                ('MAX_AGE', models.IntegerField()),
                ('BANK_ACC_NO', models.BooleanField()),
                ('EDUCATIONAL_QUALIFICATION', models.CharField(max_length=30)),
                ('IS_INDIAN', models.BooleanField()),
                ('SAVINGS_ACC', models.BooleanField()),
                ('MAX_NO_OF_GIRL_CHILDREN', models.IntegerField()),
                ('MAX_NO_OF_CHILDREN', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('female', 'female')], max_length=10)),
                ('CASTE', models.CharField(max_length=20)),
                ('MARITAL_STATUS', models.BooleanField()),
                ('MIN_SALARY', models.IntegerField()),
                ('MAX_SALARY', models.IntegerField()),
                ('PREGNANT', models.BooleanField()),
                ('FARMER', models.BooleanField()),
                ('NO_OF_WORKING_YEARS', models.IntegerField()),
                ('MARKS_PERCENT', models.IntegerField()),
                ('EXCELLED_IN_ANY_SPOT', models.TextField()),
                ('EMPLOYED', models.BooleanField()),
                ('DISABLED', models.BooleanField()),
                ('IS_ENTREPRENEUR', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='scheme_criteria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scheme_criteria_vertical'),
        ),
    ]
