# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='EXCELLED_IN_ANY_SPOT',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MARKS_PERCENT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MAX_AGE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MAX_NO_OF_CHILDREN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MAX_NO_OF_GIRL_CHILDREN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MAX_SALARY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MIN_AGE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='MIN_SALARY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme_criteria_vertical',
            name='NO_OF_WORKING_YEARS',
            field=models.IntegerField(null=True),
        ),
    ]
