# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='required_documents',
            field=models.ManyToManyField(to='app.Documents'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme_criteria',
            name='name',
            field=models.CharField(choices=[('MIN_AGE', 'MIN_AGE'), ('MAX_AGE', 'MAX_AGE'), ('BANK_ACC_NO', 'BANK_ACC_NO'), ('EDUCATIONAL_QUALIFICATION', 'EDUCATIONAL_QUALIFICATION'), ('NATIONALITY', 'NATIONALITY'), ('SAVINGS_ACC', 'SAVINGS_ACC'), ('MAX_NO_OF_GIRL_CHILDREN', 'MAX_NO_OF_GIRL_CHILDREN'), ('MAX_NO_OF_CHILDREN', 'MAX_NO_OF_CHILDREN'), ('GENDER', 'GENDER'), ('CASTE', 'CASTE'), ('MARITAL_STATUS', 'MARITAL_STATUS'), ('MIN_SALARY', 'MIN_SALARY'), ('MAX_SALARY', 'MAX_SALARY'), ('PREGNANT', 'PREGNANT'), ('FARMER', 'FARMER'), ('NO_OF_WORKING_YEARS', 'NO_OF_WORKING_YEARS'), ('NO_OF_WORKING_YEARS', 'NO_OF_WORKING_YEARS'), ('EXCELLED_IN_ANY_SPOT', 'EXCELLED_IN_ANY_SPOT'), ('EMPLOYED', 'EMPLOYED'), ('DISABLED', 'DISABLED'), ('IS_ENTREPRENEUR', 'IS_ENTREPRENEUR')], max_length=30),
        ),
    ]
