# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_salaray', models.IntegerField()),
                ('req_community', models.CharField(max_length=4)),
                ('scheme_name', models.CharField(max_length=30)),
            ],
        ),
    ]
