# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme_criteria',
            name='Required_documents',
        ),
        migrations.RemoveField(
            model_name='scheme_criteria',
            name='scheme',
        ),
        migrations.AddField(
            model_name='post',
            name='criteria',
            field=models.ManyToManyField(to='app.Scheme_criteria'),
        ),
    ]
