# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApplyScheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfSchemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_of_scheme', models.CharField(choices=[('AP', 'applied'), ('CH', 'verification'), ('TR', 'transaction on process'), ('CO', 'finished transaction')], default='AP', max_length=2)),
                ('Scheme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyScheme.AppliedSchemes')),
            ],
        ),
    ]
