# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApplyScheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfSchemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_of_scheme', models.CharField(choices=[(b'AP', b'applied'), (b'CH', b'verification'), (b'TR', b'transaction on process'), (b'CO', b'finished transaction')], default=b'AP', max_length=2)),
                ('applied_Date', models.DateTimeField(auto_now_add=True)),
                ('Scheme_id', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='ApplyScheme.AppliedSchemes')),
            ],
        ),
    ]
