# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofschemes',
            name='Scheme_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ApplyScheme.AppliedSchemes'),
        ),
        migrations.AlterField(
            model_name='statusofschemes',
            name='Status_of_scheme',
            field=models.CharField(choices=[('AP', 'applied'), ('CH', 'verification'), ('TR', 'transaction on process'), ('CO', 'finished transaction')], default='AP', max_length=3),
        ),
    ]
