# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Status', '0003_auto_20170329_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusofschemes',
            name='applied_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
